### ISSUE TITLE
Compile for mac?

### ISSUE THREAD

**Issue by condr-at** [deleterium/signum-vanity-opencl#5]
Is there any way to compile this on mac?

**Comment by deleterium** [comment]
To compile on mac should be easy. But I don't have one available...

You can try to clone the repository, change to dev branch and run "make" at the directory. Maybe it works!

**Comment by condr-at** [comment]
Cannot write the correct Makefile. Need help(
I tried this:
`CC = cc
CFLAGS = -std=c99 -pedantic -Wall
OBJECTS = main.o

all: main

main.o: main.c
	$(CC) $(CFLAGS) -c main.c

appname: $(OBJECTS)
	$(CC) $(OBJECTS) -o main

clean:
	rm -f *.o main`

Output errors were:
`ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [main] Error 1
`

**Comment by deleterium** [comment]
- Download source code for the dev branch: https://github.com/deleterium/signum-vanity-opencl/archive/refs/heads/dev.zip
- Extract the file at some folder
- Open a terminal and go that folder
- Run the command `make`
- Check compilation errors/warning. If the compilation was successful, then you have an executable file at `dist` folder.

**Comment by condr-at** [comment]
> * Download source code for the dev branch: https://github.com/deleterium/signum-vanity-opencl/archive/refs/heads/dev.zip
> * Extract the file at some folder
> * Open a terminal and go that folder
> * Run the command `make`
> * Check compilation errors/warning. If the compilation was successful, then you have an executable file at `dist` folder.

`gcc -c -o build/ed25519-donna.o src/ed25519-donna/ed25519.c -O2 -Wextra
error: unable to open output file 'build/ed25519-donna.o': 'No such file or directory'
1 error generated.
make: *** [build/ed25519-donna.o] Error 1
`

**Comment by deleterium** [comment]
Two directories are missing. You need to create them and try again:
- Run the command `mkdir dist`
- Run the command `mkdir build`
- Run the command `make`

**Comment by condr-at** [comment]
Thank you, @deleterium !!!

Here's steps for mac:

```
cd Downloads/signum-vanity-opencl-dev
mkdir dist
mkdir build

* Open the file Makefile * Edit line 4. Replace the option -lOpenCL with -framework OpenCL

make
cd dist
./vanity --options "A?A"
./vanity --help

./vanity --suffix DELET --gpu-work-size 32
⇅ or
./vanity --suffix DELET --gpu-work-size 1
```
