### ISSUE TITLE
Nvidia GTX 1070 - CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by gittrekt** [deleterium/signum-vanity-opencl#7]
Seems like an issue specifically with a the 1070. I have an old 760 that works fine. Tried reducing work group size and threads and neither seems to resolve it. Any ideas?

GPU platform 0 details:
    Platform name...........: NVIDIA CUDA
Details for device 0:
    Device..................: NVIDIA GeForce GTX 1070
    Hardware version........: OpenCL 3.0 CUDA
    Software version........: 470.129.06
    OpenCL C version........: OpenCL C 1.2
    Parallel compute units..: 15
    Max Work Group Size.....: 1024
Compiling OpenCL kernel: Done!
Using mask REKT-????-????-?????
 2414434 tries for 90% chance finding a match. Ctrl + C to cancel.
OpenCL error -5 at debug position 53:
CL_OUT_OF_RESOURCES        if there is a failure to allocate resources required by the OpenCL implementation on the device.

**Comment by deleterium** [comment]
I would say you to try option `--gpu-work-size 32 --gpu-threads 256`

The two graphics are on same computer?
If yes, there are more strange cases with dual graphics on same mainboard...

**Comment by gittrekt** [comment]
I didn't realize I had to reduce the work size by so much. Work size 512+ results in a memory failure. 

`--gpu-work-size 256 --gpu-threads 8388608` Appears to have best performance with approx 2,340,000/s, with 165/166w and temps around 80C. 
I found 30720 threads (15 MP cores * 2048 threads) to be optimal for temps at 58C and about 121/166W and 2,161,000.
